#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    methods: GET|POST|PUT|DELETE

# ESTACIONES
estaciones:
    path: /estaciones
    controller: App\Controller\EstacionController::estaciones
    methods: GET|POST

estacion:
    path: /estacion/{id}
    controller: App\Controller\EstacionController::estacion
    methods: GET|PUT|DELETE

rutas_estacion:
    path: /estacion/{id}/rutas
    controller: App\Controller\EstacionController::rutasEstacion
    methods: GET

ruta_estacion:
    path: /estacion/{idEstacion}/ruta/{idRuta}
    controller: App\Controller\EstacionController::rutaEstacion
    methods: POST|DELETE

# PLANES DE VIAJE
planes_viaje:
    path: /planesViaje
    controller: App\Controller\PlanViajeController::planesViaje
    methods: GET|POST

plan_viaje:
    path: /planViaje/{id}
    controller: App\Controller\PlanViajeController::planViaje
    methods: GET|PUT|DELETE

plan_viaje_puntos_interes:
    path: /planViaje/{id}/puntosInteres
    controller: App\Controller\PlanViajeController::planViajePuntosInteres
    methods: GET

add_punto_interes_plan_viaje:
    path: /planViaje/{idPlanViaje}/puntosInteres/{idPuntoInteres}
    controller: App\Controller\PlanViajeController::addPuntoInteresPlanViaje
    methods: POST|DELETE

planes_viaje_usuario:
    path: /planesViaje/usuario/{id}
    controller: App\Controller\PlanViajeController::planesViajeUsuario
    methods: GET|POST

# PUNTOS DE INTERÉS
puntos_interes:
    path: /puntosInteres
    controller: App\Controller\PuntoInteresController::puntosInteres
    methods: GET|POST

punto_interes:
    path: /puntoInteres/{id}
    controller: App\Controller\PuntoInteresController::puntoInteres
    methods: GET|PUT|DELETE

punto_interes_estacion:
    path: /puntosInteres/estacion/{idEstacion}
    controller: App\Controller\PuntoInteresController::puntosInteresEstacion
    methods: GET|POST

# RUTAS
rutas:
    path: /rutas
    controller: App\Controller\RutaController::rutas
    methods: GET|POST

ruta:
    path: /ruta/{id}
    controller: App\Controller\RutaController::ruta
    methods: GET|PUT|DELETE

tren_ruta:
    path: /ruta/{id}/tren
    controller: App\Controller\RutaController::trenRuta
    methods: GET|DELETE

add_tren_ruta:
    path: /ruta/{idRuta}/tren/{idTren}
    controller: App\Controller\RutaController::addTrenRuta
    methods: POST

estaciones_ruta:
    path: /ruta/{id}/estaciones
    controller: App\Controller\RutaController::estacionesRuta
    methods: GET

estacion_ruta:
    path: /ruta/{idRuta}/estacion/{idEstacion}
    controller: App\Controller\RutaController::estacionRuta
    methods: POST|DELETE

# TRENES
trenes:
    path: /trenes
    controller: App\Controller\TrenController::trenes
    methods: GET|POST

tren:
    path: /tren/{id}
    controller: App\Controller\TrenController::tren
    methods: GET|PUT|DELETE

# USUARIOS
usuarios:
    path: /usuarios
    controller: App\Controller\UsuarioController::usuarios
    methods: GET|POST

usuario:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::usuario
    methods: GET|PUT|DELETE
